# Generated by Django 4.1.3 on 2022-12-03 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurant_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='author_id',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
