# Generated by Django 4.1.3 on 2022-12-03 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_restaurant_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='author_id',
        ),
    ]
