# Generated by Django 4.1.3 on 2022-12-03 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='likes',
            new_name='author_id',
        ),
    ]
