# Generated by Django 4.1.3 on 2022-12-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurant_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='a_id',
            field=models.IntegerField(default=0),
        ),
    ]
