# Generated by Django 4.1.3 on 2022-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_rename_a_id_restaurant_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resenha',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
