# Generated by Django 4.1.3 on 2022-12-03 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_remove_resenha_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
