# Generated by Django 4.1.3 on 2022-12-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0013_resenha_date_resenha_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resenha',
            name='text',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
