# Generated by Django 4.1.3 on 2022-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0015_rename_date_resenha_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='comida',
            field=models.CharField(default='Faltando', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='endereco',
            field=models.CharField(default='Faltando', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='preco',
            field=models.CharField(default='Faltando', max_length=255),
        ),
    ]
