# Generated by Django 4.1.3 on 2022-12-04 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0017_restaurant_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='comida',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='endereco',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='preco',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
