# Generated by Django 4.1.3 on 2022-12-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0018_alter_restaurant_comida_alter_restaurant_endereco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avr',
            field=models.FloatField(default=0),
        ),
    ]
