# Generated by Django 4.1.3 on 2022-12-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0020_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='aprove',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='standby',
            field=models.BooleanField(default=False),
        ),
    ]
